'use client';
import { Canvas, type ThreeEvent, useThree } from '@react-three/fiber';
import { Grid, Html, Line, OrbitControls, Sky, Stars, useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { Suspense, useEffect, useLayoutEffect, useMemo, useRef } from 'react';
import { manhattanContext } from '@skyfoundry/fixture-projects';
import { materials } from '@skyfoundry/procedural-assets';
import { taskProgress } from '@skyfoundry/construction-engine';
import type { Component } from '@skyfoundry/scene-schema';
import { demo, useStudio } from '@/lib/store';

const tasks=new Map(demo.tasks.map(t=>[t.id,t]));
const systemFor=(c:Component)=> c.type==='pile'||c.type==='foundation_mat'||c.type==='excavation'?'foundation':c.type.includes('core')?'core':['column','beam','brace'].includes(c.type)?'structure':c.type==='slab'?'slabs':['curtain_wall_panel','mullion','spandrel','parapet','crown'].includes(c.type)?'facade':['tower_crane','hoist','scaffold','excavator','concrete_truck','flatbed_truck','material_stack','fence'].includes(c.type)?'equipment':c.type==='worker'?'workers':['tree','bench','planter'].includes(c.type)?'landscape':'structure';
const isCylinder=(c:Component)=>['pile','worker','tree','streetlight'].includes(c.type);
const dim=(c:Component,k:string,f=1)=>typeof c.parameters[k]==='number'?c.parameters[k] as number:f;
const visualProgress=(c:Component,tick:number)=>{const task=c.taskId?tasks.get(c.taskId):undefined;if(!task)return tick>0?1:0;let p=taskProgress(task,tick);if(c.metadata.removeAfterTick&&tick>(c.metadata.removeAfterTick as number))p=Math.max(0,1-(tick-(c.metadata.removeAfterTick as number))/30);return p};

type StaticInstance={position:[number,number,number];scale:[number,number,number]};
function StaticBoxInstances({items,color}:{items:StaticInstance[];color:string}){const ref=useRef<THREE.InstancedMesh>(null);useLayoutEffect(()=>{if(!ref.current)return;const matrix=new THREE.Matrix4();for(let i=0;i<items.length;i++){const item=items[i]!;matrix.makeScale(...item.scale);matrix.setPosition(...item.position);ref.current.setMatrixAt(i,matrix)}ref.current.instanceMatrix.needsUpdate=true},[items]);return <instancedMesh ref={ref} args={[undefined,undefined,items.length]} receiveShadow><boxGeometry/><meshStandardMaterial color={color} roughness={.74}/></instancedMesh>}
function StaticCylinderInstances({items,color,sphere=false}:{items:StaticInstance[];color:string;sphere?:boolean}){const ref=useRef<THREE.InstancedMesh>(null);useLayoutEffect(()=>{if(!ref.current)return;const matrix=new THREE.Matrix4();for(let i=0;i<items.length;i++){const item=items[i]!;matrix.makeScale(...item.scale);matrix.setPosition(...item.position);ref.current.setMatrixAt(i,matrix)}ref.current.instanceMatrix.needsUpdate=true},[items]);return <instancedMesh ref={ref} args={[undefined,undefined,items.length]}>{sphere?<sphereGeometry args={[1,8,6]}/>:<cylinderGeometry args={[1,1,1,8]}/>}<meshStandardMaterial color={color} roughness={.9}/></instancedMesh>}

function CityContext(){const shown=useStudio(s=>s.systems.context),camera=useStudio(s=>s.camera);const bodies=useMemo(()=>manhattanContext.map(b=>{const h=b.h*.68;return{position:[b.x,h/2,b.z] as [number,number,number],scale:[b.w,h,b.d] as [number,number,number]}}),[]),roofs=useMemo(()=>manhattanContext.map(b=>{const h=b.h*.68;return{position:[b.x,h+.12,b.z] as [number,number,number],scale:[b.w*.82,.25,b.d*.82] as [number,number,number]}}),[]),trunks=useMemo(()=>Array.from({length:20},(_,i)=>({position:[-86+i*9,2.4,-27] as [number,number,number],scale:[.18,4.8,.18] as [number,number,number]})),[]),crowns=useMemo(()=>Array.from({length:20},(_,i)=>({position:[-86+i*9,5.2,-27] as [number,number,number],scale:[1.5,1.5,1.5] as [number,number,number]})),[]);if(!shown||camera==='section_x'||camera==='section_z')return null;return <group>
  <mesh receiveShadow position={[0,-.55,0]}><boxGeometry args={[190,1,150]}/><meshStandardMaterial color="#1b2227" roughness={.96}/></mesh>
  <mesh receiveShadow position={[0,.015,-34]}><boxGeometry args={[190,.08,17]}/><meshStandardMaterial color="#12181d" roughness={.9}/></mesh>
  <mesh receiveShadow position={[0,.02,34]}><boxGeometry args={[190,.08,17]}/><meshStandardMaterial color="#12181d" roughness={.9}/></mesh>
  <mesh receiveShadow position={[-42,.025,0]}><boxGeometry args={[17,.1,150]}/><meshStandardMaterial color="#141a1f" roughness={.9}/></mesh>
  <mesh receiveShadow position={[42,.025,0]}><boxGeometry args={[17,.1,150]}/><meshStandardMaterial color="#141a1f" roughness={.9}/></mesh>
  <StaticBoxInstances items={bodies} color="#4d5960"/><StaticBoxInstances items={roofs} color="#899197"/><StaticCylinderInstances items={trunks} color="#333c40"/><StaticCylinderInstances items={crowns} color="#365b49" sphere/>
  <Grid args={[180,140]} position={[0,.08,0]} cellSize={5} cellThickness={.25} cellColor="#677179" sectionSize={20} sectionThickness={.45} sectionColor="#87939a" fadeDistance={160} fadeStrength={1}/>
  <Line points={[[-95,.12,-25],[95,.12,-25]]} color="#d4aa62" lineWidth={1} dashed dashSize={2} gapSize={6}/>
  <Line points={[[-95,.12,25],[95,.12,25]]} color="#d4aa62" lineWidth={1} dashed dashSize={2} gapSize={6}/>
  </group>}

function materialProps(id:string|undefined,mode:string,selected=false){const m=materials[id??'concrete']??materials.concrete!;if(mode==='clay')return{color:selected?'#ffb057':'#aeb4b3',roughness:.78,metalness:.02,opacity:1};if(mode==='structure')return{color:selected?'#fff0a8':id==='dark_steel'?'#ef7f45':id==='concrete'?'#63a4b5':'#d9c55a',roughness:.55,metalness:.15,opacity:1};if(mode==='xray')return{color:selected?'#ffb057':m.color,roughness:m.roughness,metalness:m.metalness,opacity:.24};return{color:selected?'#ffd07a':m.color,roughness:m.roughness,metalness:m.metalness,opacity:m.opacity??1,emissive:mode==='night'?(m.emissive??(id==='blue_glass'?'#162d39':'#000000')):(m.emissive??'#000000'),emissiveIntensity:mode==='night'?(m.emissiveIntensity??.45):(m.emissive?0.18:0)} }

function InstanceBucket({items,cylinder=false}:{items:Component[];cylinder?:boolean}){
  const ref=useRef<THREE.InstancedMesh>(null);const tick=useStudio(s=>s.tick),mode=useStudio(s=>s.mode),section=useStudio(s=>s.camera),select=useStudio(s=>s.select);
  const matrix=useMemo(()=>new THREE.Matrix4(),[]);const pos=useMemo(()=>new THREE.Vector3(),[]),quat=useMemo(()=>new THREE.Quaternion(),[]),scale=useMemo(()=>new THREE.Vector3(),[]);const euler=useMemo(()=>new THREE.Euler(),[]);
  useLayoutEffect(()=>{if(!ref.current)return;ref.current.instanceMatrix.setUsage(THREE.DynamicDrawUsage);items.forEach((c,i)=>{let p=visualProgress(c,tick);const [x,y,z]=c.transform.position;if((section==='section_x'&&x>1)||(section==='section_z'&&z>1))p=0;const moving=c.type==='worker'?Math.sin((tick+i*13)*.035)*2:0;const vehicle=['concrete_truck','flatbed_truck','excavator'].includes(c.type)?Math.sin(tick*.012+i)*3:0;pos.set(x+moving+vehicle,y,z);euler.set(...c.transform.rotation.map(v=>THREE.MathUtils.degToRad(v)) as [number,number,number]);quat.setFromEuler(euler);
    if(cylinder){const r=dim(c,'radius',.3),h=dim(c,'height',1);scale.set(r*p,h*p,r*p)}else{const w=dim(c,'width',dim(c,'length',1)),h=dim(c,'height',1),d=dim(c,'depth',.5);const grow=c.type==='excavation'?Math.max(.01,p):p;scale.set(w*grow,h*grow,d*grow)}matrix.compose(pos,quat,scale);ref.current!.setMatrixAt(i,matrix)});ref.current.instanceMatrix.needsUpdate=true},[items,tick,section,cylinder,euler,matrix,pos,quat,scale]);
  const props=materialProps(items[0]?.materialId,mode);return <instancedMesh ref={ref} args={[undefined,undefined,items.length]} frustumCulled={false} castShadow={items[0]?.type!=='curtain_wall_panel'} receiveShadow onClick={(e:ThreeEvent<MouseEvent>)=>{e.stopPropagation();if(e.instanceId!==undefined)select(items[e.instanceId]?.id)}}>
    {cylinder?<cylinderGeometry args={[1,1,1,12]}/>:<boxGeometry args={[1,1,1]}/>}<meshStandardMaterial {...props} transparent={props.opacity<1} depthWrite={props.opacity>.4}/>
  </instancedMesh>
}

function Components(){const components=useStudio(s=>s.components),systems=useStudio(s=>s.systems),hidden=useStudio(s=>s.hiddenIds);const filtered=components.filter(c=>!hidden.includes(c.id)&&systems[systemFor(c)]&&c.type!=='tower_crane'&&c.type!=='crown'&&c.generator!=='cad_extruded_profile');const buckets=useMemo(()=>{const map=new Map<string,Component[]>();for(const c of filtered){const key=`${isCylinder(c)?'cyl':'box'}:${c.materialId??'concrete'}:${c.type==='excavation'?'excavation':'default'}`;map.set(key,[...(map.get(key)??[]),c])}return [...map.entries()]},[filtered]);return <>{buckets.map(([key,items])=><InstanceBucket key={key} items={items} cylinder={key.startsWith('cyl')}/>)}</>}

function CadPlanter(){const planter=useStudio(s=>s.components.find(c=>c.generator==='cad_extruded_profile')),tick=useStudio(s=>s.tick),shown=useStudio(s=>s.systems.landscape),select=useStudio(s=>s.select);const gltf=useGLTF('/assets/cad/planter.glb');const object=useMemo(()=>gltf.scene.clone(true),[gltf.scene]);useEffect(()=>{object.traverse(node=>{if(node instanceof THREE.Mesh){node.material=new THREE.MeshStandardMaterial({color:'#b7aa95',roughness:.82});node.castShadow=true;node.receiveShadow=true}})},[object]);if(!planter||!shown)return null;const p=visualProgress(planter,tick);return <group name="cad-planter-import" position={planter.transform.position} rotation={planter.transform.rotation.map(v=>THREE.MathUtils.degToRad(v)) as [number,number,number]} scale={[p,p,p]} onClick={e=>{e.stopPropagation();select(planter.id)}}><primitive object={object}/></group>}

function Crown(){const crown=useStudio(s=>s.components.find(c=>c.type==='crown')),tick=useStudio(s=>s.tick),mode=useStudio(s=>s.mode),select=useStudio(s=>s.select),section=useStudio(s=>s.camera);if(!crown||section==='section_x')return null;const p=visualProgress(crown,tick),h=dim(crown,'height',12),w=dim(crown,'width',20),taper=dim(crown,'taper',.58);return <group position={[0,112,0]} scale={[p,p,p]} onClick={e=>{e.stopPropagation();select(crown.id)}}>
  <mesh position={[0,-h*.26,0]} rotation={[0,Math.PI/4,0]} castShadow><cylinderGeometry args={[w*.5,w*.62,h*.48,4]}/><meshStandardMaterial {...materialProps(crown.materialId,mode)} /></mesh>
  <mesh position={[0,h*.24,0]} rotation={[0,Math.PI/4,0]} castShadow><cylinderGeometry args={[w*taper*.32,w*.5,h*.52,4]}/><meshStandardMaterial {...materialProps(crown.materialId,mode)} /></mesh>
  <group position={[0,h*.55,0]}>{Array.from({length:7},(_,i)=><mesh key={i} position={[-4.5+i*1.5,0,0]}><sphereGeometry args={[.55,8,6]}/><meshStandardMaterial color="#4f8a55" roughness={.9}/></mesh>)}</group>
  </group>}

function Crane(){const tick=useStudio(s=>s.tick),shown=useStudio(s=>s.systems.equipment),mode=useStudio(s=>s.mode);if(!shown)return null;const p=Math.min(1,tick/100),slew=Math.sin(tick*.009)*.4,trolley=6+Math.sin(tick*.026)*10,hookY=75+Math.sin(tick*.018)*18;const mat=materialProps('safety_orange',mode);return <group position={[25,0,12]} scale={[1,p,1]} rotation={[0,slew,0]}>
  <mesh position={[0,62,0]} castShadow><boxGeometry args={[1.4,124,1.4]}/><meshStandardMaterial {...mat}/></mesh><mesh position={[-8,123,0]} castShadow><boxGeometry args={[34,1.1,1.1]}/><meshStandardMaterial {...mat}/></mesh><mesh position={[13,123,0]}><boxGeometry args={[8,2,2.4]}/><meshStandardMaterial color="#273139" metalness={.65}/></mesh>
  <Line points={[[trolley,122.5,0],[trolley,hookY,0]]} color="#252b2e" lineWidth={1}/><mesh position={[trolley,hookY,0]}><boxGeometry args={[2,.6,2]}/><meshStandardMaterial color="#d38d3f"/></mesh>
  </group>}

function Selection(){const id=useStudio(s=>s.selectedId),components=useStudio(s=>s.components),tick=useStudio(s=>s.tick);const c=components.find(x=>x.id===id);if(!c||c.type==='crown')return null;const p=visualProgress(c,tick);if(p<=0)return null;const w=dim(c,'width',dim(c,'radius',.3)*2),h=dim(c,'height',1),d=dim(c,'depth',dim(c,'radius',.3)*2);return <mesh position={c.transform.position} rotation={c.transform.rotation.map(v=>THREE.MathUtils.degToRad(v)) as [number,number,number]}><boxGeometry args={[w*1.05,h*1.05,d*1.05]}/><meshBasicMaterial color="#ffd27d" wireframe transparent opacity={.95}/></mesh>}

const views={overview:{pos:[95,180,105],target:[0,45,0]},street:{pos:[38,18,42],target:[0,28,0]},crane:{pos:[-18,108,58],target:[15,76,7]},section_x:{pos:[88,54,0],target:[0,48,0]},section_z:{pos:[0,54,88],target:[0,48,0]},top:{pos:[.01,160,.01],target:[0,0,0]}} as const;
function CameraRig(){const preset=useStudio(s=>s.camera),selectedId=useStudio(s=>s.selectedId),components=useStudio(s=>s.components),{camera}=useThree(),controls=useRef<any>(null);const selected=components.find(c=>c.id===selectedId);const v=useMemo(()=>preset==='selected'&&selected?{pos:[selected.transform.position[0]+15,selected.transform.position[1]+10,selected.transform.position[2]+15] as const,target:selected.transform.position}:views[preset==='selected'?'overview':preset],[preset,selected]);useEffect(()=>{camera.position.set(v.pos[0],v.pos[1],v.pos[2]);camera.lookAt(v.target[0],v.target[1],v.target[2]);if(controls.current){controls.current.target.set(v.target[0],v.target[1],v.target[2]);controls.current.update()}},[camera,v]);return <OrbitControls ref={controls} makeDefault target={[v.target[0],v.target[1],v.target[2]]} enableDamping dampingFactor={.08} minDistance={4} maxDistance={240} maxPolarAngle={Math.PI*.495}/>} 

function Lighting(){const mode=useStudio(s=>s.mode);const night=mode==='night';return <><ambientLight intensity={night?.28:.65}/><hemisphereLight intensity={night?.35:.75} color={night?'#7394c8':'#d8edff'} groundColor="#1c2428"/><directionalLight position={[45,95,35]} intensity={night?.35:2.2} color={night?'#8ba8d8':'#fff1d7'} castShadow shadow-mapSize={[2048,2048]} shadow-camera-far={240} shadow-camera-left={-85} shadow-camera-right={85} shadow-camera-top={120} shadow-camera-bottom={-50}/>{night?<Stars radius={170} depth={70} count={1500} factor={3}/>:<Sky distance={450000} sunPosition={[60,35,45]} turbidity={7} rayleigh={1.5}/>}<fog attach="fog" args={[night?'#071018':'#b8c9ce',100,260]}/></>}

function SceneReady(){const {gl,camera,scene,invalidate}=useThree();useEffect(()=>{(window as any).__SKYFOUNDRY_CANVAS__=gl.domElement;(window as any).__SKYFOUNDRY_RENDERER__=gl;(window as any).__SKYFOUNDRY_CAMERA__=camera;(window as any).__SKYFOUNDRY_SCENE__=scene;invalidate();const first=requestAnimationFrame(()=>requestAnimationFrame(()=>{if(!gl.getContext().isContextLost()&&gl.info.render.calls>0)document.documentElement.dataset.sceneReady='true'}));return()=>{cancelAnimationFrame(first);delete document.documentElement.dataset.sceneReady;delete (window as any).__SKYFOUNDRY_CANVAS__;delete (window as any).__SKYFOUNDRY_RENDERER__}},[gl,camera,scene,invalidate]);return null}

export default function Scene(){const mode=useStudio(s=>s.mode),select=useStudio(s=>s.select);return <Canvas data-testid="construction-canvas" frameloop="demand" shadows={false} dpr={1} camera={{position:[95,180,105],fov:42,near:.1,far:600}} gl={{antialias:false,preserveDrawingBuffer:false,localClippingEnabled:true}} onPointerMissed={()=>select(undefined)}>
  <color attach="background" args={[mode==='night'?'#071018':'#b8c9ce']}/><Lighting/><CityContext/><Components/><Suspense fallback={null}><CadPlanter/></Suspense><Crown/><Crane/><Selection/><CameraRig/><SceneReady/><Html position={[0,118,0]} center distanceFactor={30} style={{pointerEvents:'none'}}><div className="scene-label">SKYFOUNDRY / TOWER A</div></Html>
  </Canvas>}
