'use client';
import { Canvas, type ThreeEvent, useThree } from '@react-three/fiber';
import { Grid, Html, Line, OrbitControls, Sky, Stars, useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { Suspense, useEffect, useLayoutEffect, useMemo, useRef } from 'react';
import { manhattanContext } from '@skyfoundry/fixture-projects';
import { materials } from '@skyfoundry/procedural-assets';
import { taskProgress } from '@skyfoundry/construction-engine';
import type { Component } from '@skyfoundry/scene-schema';
import { demo, useStudio } from '@/lib/store';

const tasks=new Map(demo.tasks.map(t=>[t.id,t]));
const systemFor=(c:Component)=> c.type==='pile'||c.type==='foundation_mat'||c.type==='excavation'?'foundation':c.type.includes('core')?'core':['column','beam','brace'].includes(c.type)?'structure':c.type==='slab'?'slabs':['curtain_wall_panel','mullion','spandrel','parapet','crown'].includes(c.type)?'facade':['tower_crane','hoist','scaffold','excavator','concrete_truck','flatbed_truck','material_stack','fence'].includes(c.type)?'equipment':c.type==='worker'?'workers':['tree','bench','planter'].includes(c.type)?'landscape':'structure';
const isCylinder=(c:Component)=>['pile','worker','tree','streetlight'].includes(c.type);
const dim=(c:Component,k:string,f=1)=>typeof c.parameters[k]==='number'?c.parameters[k] as number:f;
const visualProgress=(c:Component,tick:number)=>{const task=c.taskId?tasks.get(c.taskId):undefined;if(!task)return tick>0?1:0;let p=taskProgress(task,tick);if(c.metadata.removeAfterTick&&tick>(c.metadata.removeAfterTick as number))p=Math.max(0,1-(tick-(c.metadata.removeAfterTick as number))/30);return p};

type StaticInstance={position:[number,number,number];scale:[number,number,number]};
function StaticBoxInstances({items,color,emissive='#000000',emissiveIntensity=0}:{items:StaticInstance[];color:string;emissive?:string;emissiveIntensity?:number}){const ref=useRef<THREE.InstancedMesh>(null);useLayoutEffect(()=>{if(!ref.current)return;const matrix=new THREE.Matrix4();for(let i=0;i<items.length;i++){const item=items[i]!;matrix.makeScale(...item.scale);matrix.setPosition(...item.position);ref.current.setMatrixAt(i,matrix)}ref.current.instanceMatrix.needsUpdate=true},[items]);return <instancedMesh ref={ref} args={[undefined,undefined,items.length]} receiveShadow><boxGeometry/><meshStandardMaterial color={color} roughness={.74} emissive={emissive} emissiveIntensity={emissiveIntensity}/></instancedMesh>}
function StaticCylinderInstances({items,color,sphere=false}:{items:StaticInstance[];color:string;sphere?:boolean}){const ref=useRef<THREE.InstancedMesh>(null);useLayoutEffect(()=>{if(!ref.current)return;const matrix=new THREE.Matrix4();for(let i=0;i<items.length;i++){const item=items[i]!;matrix.makeScale(...item.scale);matrix.setPosition(...item.position);ref.current.setMatrixAt(i,matrix)}ref.current.instanceMatrix.needsUpdate=true},[items]);return <instancedMesh ref={ref} args={[undefined,undefined,items.length]}>{sphere?<sphereGeometry args={[1,8,6]}/>:<cylinderGeometry args={[1,1,1,8]}/>}<meshStandardMaterial color={color} roughness={.9}/></instancedMesh>}

function CityContext(){const shown=useStudio(s=>s.systems.context),camera=useStudio(s=>s.camera),mode=useStudio(s=>s.mode),tick=useStudio(s=>s.tick),night=mode==='night';
  const bodies=useMemo(()=>manhattanContext.map(b=>{const h=b.h*.74;return{position:[b.x,h/2,b.z] as [number,number,number],scale:[b.w,h,b.d] as [number,number,number]}}),[]);
  const setbacks=useMemo(()=>manhattanContext.filter((_,i)=>i%2===0).map(b=>{const h=b.h*.74;return{position:[b.x,h+Math.min(12,h*.12)/2,b.z] as [number,number,number],scale:[b.w*.72,Math.min(12,h*.12),b.d*.72] as [number,number,number]}}),[]);
  const roofs=useMemo(()=>manhattanContext.map(b=>{const h=b.h*.74;return{position:[b.x,h+.15,b.z] as [number,number,number],scale:[b.w*.82,.3,b.d*.82] as [number,number,number]}}),[]);
  const roofGear=useMemo(()=>manhattanContext.filter((_,i)=>i%3===0).map(b=>{const h=b.h*.74;return{position:[b.x+b.w*.16,h+1.6,b.z-b.d*.12] as [number,number,number],scale:[Math.min(4,b.w*.2),3,Math.min(5,b.d*.24)] as [number,number,number]}}),[]);
  const windows=useMemo(()=>manhattanContext.flatMap((b,bi)=>{const h=b.h*.74,floors=Math.max(4,Math.floor(h/4)),rows:StaticInstance[]=[];for(let floor=1;floor<floors;floor+=2){const y=floor*4;for(let x=-b.w*.34;x<=b.w*.34;x+=5.2)rows.push({position:[b.x+x,y,b.z+(b.z<0?b.d/2+.03:-b.d/2-.03)],scale:[2.2,1.15,.08]});for(let z=-b.d*.3;z<=b.d*.3;z+=5.2)rows.push({position:[b.x+(b.x<0?b.w/2+.03:-b.w/2-.03),y,b.z+z],scale:[.08,1.15,2.2]})}return rows.filter((_,i)=>(i+bi)%3!==0)}),[]);
  const trunks=useMemo(()=>Array.from({length:22},(_,i)=>({position:[-91+i*8.7,2.25,-23] as [number,number,number],scale:[.16,4.5,.16] as [number,number,number]})),[]);
  const crowns=useMemo(()=>Array.from({length:22},(_,i)=>({position:[-91+i*8.7,5.15,-23] as [number,number,number],scale:[1.45+(i%3)*.15,1.6,1.45+(i%2)*.2] as [number,number,number]})),[]);
  const crosswalks=useMemo(()=>[-50,-34,34,50].flatMap((x,xi)=>Array.from({length:7},(_,i)=>({position:[x+(xi<2?i*2.2:0),.14,xi<2?-34:-26+i*2.2] as [number,number,number],scale:[xi<2?1.2:8,.025,xi<2?8:1.2] as [number,number,number]}))),[]);
  const lamps=useMemo(()=>Array.from({length:18},(_,i)=>({position:[-82+i*9.5,3.2,i%2?-22:22] as [number,number,number],scale:[.11,6.4,.11] as [number,number,number]})),[]);
  const lampHeads=useMemo(()=>lamps.map(item=>({position:[item.position[0],6.25,item.position[2]] as [number,number,number],scale:[.75,.18,.35] as [number,number,number]})),[lamps]);
  const traffic=useMemo(()=>Array.from({length:10},(_,i)=>{const east=i<6,x=-94+((tick*.055+i*31)%188),z=east?(i%2?-29:-39):(i%2?38:29),dir=i%2?1:-1;return{position:[dir>0?x:-x,.72,z] as [number,number,number],scale:[3.4,.75,1.55] as [number,number,number]}}),[tick]);
  const cabins=useMemo(()=>traffic.map((car,i)=>({position:[car.position[0]+(i%2 ? .35 : -.35),1.45,car.position[2]] as [number,number,number],scale:[1.7,.75,1.35] as [number,number,number]})),[traffic]);
  if(!shown||camera==='section_x'||camera==='section_z')return null;return <group>
  <mesh receiveShadow position={[0,-.55,0]}><boxGeometry args={[230,1,190]}/><meshStandardMaterial color={night?'#11191f':'#303a3d'} roughness={.98}/></mesh>
  <StaticBoxInstances items={[{position:[0,.02,-34],scale:[230,.1,18]},{position:[0,.02,34],scale:[230,.1,18]},{position:[-42,.03,0],scale:[18,.1,190]},{position:[42,.03,0],scale:[18,.1,190]}]} color={night?'#080d12':'#171d20'}/>
  <StaticBoxInstances items={[{position:[0,.09,-22.7],scale:[230,.18,4.2]},{position:[0,.09,22.7],scale:[230,.18,4.2]},{position:[-30.7,.1,0],scale:[4.2,.2,190]},{position:[30.7,.1,0],scale:[4.2,.2,190]}]} color={night?'#252d31':'#71797a'}/>
  <StaticBoxInstances items={bodies} color={night?'#253038':'#667174'}/><StaticBoxInstances items={setbacks} color={night?'#303b42':'#748084'}/><StaticBoxInstances items={roofs} color={night?'#586268':'#a6adae'}/><StaticBoxInstances items={roofGear} color={night?'#39444b':'#879093'}/>
  <StaticBoxInstances items={windows} color={night?'#d8b471':'#91b1b7'} emissive={night?'#ffb752':'#000000'} emissiveIntensity={night ? .8 : 0}/>
  <StaticBoxInstances items={crosswalks} color={night?'#7a7d76':'#d3d0c4'}/>
  <StaticCylinderInstances items={trunks} color="#3a342d"/><StaticCylinderInstances items={crowns} color={night?'#203e34':'#3f6b4e'} sphere/><StaticCylinderInstances items={lamps} color="#263137"/><StaticBoxInstances items={lampHeads} color={night?'#f2c377':'#566268'} emissive={night?'#ffc66b':'#000000'} emissiveIntensity={night?1.6:0}/>
  <StaticBoxInstances items={traffic.slice(0,4)} color="#b94835"/><StaticBoxInstances items={traffic.slice(4,7)} color="#d4aa4f"/><StaticBoxInstances items={traffic.slice(7)} color="#416b86"/><StaticBoxInstances items={cabins} color={night?'#c5d4d5':'#b9d3d7'}/>
  <Grid args={[220,180]} position={[0,.135,0]} cellSize={5} cellThickness={.16} cellColor={night?'#313c42':'#657073'} sectionSize={20} sectionThickness={.32} sectionColor={night?'#435058':'#899295'} fadeDistance={190} fadeStrength={1}/>
  <Line points={[[-115,.16,-34],[115,.16,-34]]} color={night?'#c79b53':'#e5c269'} lineWidth={1} dashed dashSize={3} gapSize={7}/><Line points={[[-115,.16,34],[115,.16,34]]} color={night?'#c79b53':'#e5c269'} lineWidth={1} dashed dashSize={3} gapSize={7}/>
  </group>}

function materialProps(id:string|undefined,mode:string,selected=false){const m=materials[id??'concrete']??materials.concrete!;if(mode==='clay')return{color:selected?'#ffb057':'#aeb4b3',roughness:.78,metalness:.02,opacity:1};if(mode==='structure')return{color:selected?'#fff0a8':id==='dark_steel'?'#ef7f45':id==='concrete'?'#63a4b5':'#d9c55a',roughness:.55,metalness:.15,opacity:1};if(mode==='xray')return{color:selected?'#ffb057':m.color,roughness:m.roughness,metalness:m.metalness,opacity:.24};return{color:selected?'#ffd07a':m.color,roughness:m.roughness,metalness:m.metalness,opacity:m.opacity??1,emissive:mode==='night'?(m.emissive??(id==='blue_glass'?'#162d39':'#000000')):(m.emissive??'#000000'),emissiveIntensity:mode==='night'?(m.emissiveIntensity??.45):(m.emissive?0.18:0)} }

function InstanceBucket({items,cylinder=false}:{items:Component[];cylinder?:boolean}){
  const ref=useRef<THREE.InstancedMesh>(null);const tick=useStudio(s=>s.tick),mode=useStudio(s=>s.mode),section=useStudio(s=>s.camera),select=useStudio(s=>s.select);
  const matrix=useMemo(()=>new THREE.Matrix4(),[]);const pos=useMemo(()=>new THREE.Vector3(),[]),quat=useMemo(()=>new THREE.Quaternion(),[]),scale=useMemo(()=>new THREE.Vector3(),[]);const euler=useMemo(()=>new THREE.Euler(),[]);
  useLayoutEffect(()=>{if(!ref.current)return;ref.current.instanceMatrix.setUsage(THREE.DynamicDrawUsage);items.forEach((c,i)=>{let p=visualProgress(c,tick);const [x,y,z]=c.transform.position;if((section==='section_x'&&x>1)||(section==='section_z'&&z>1))p=0;const moving=c.type==='worker'?Math.sin((tick+i*13)*.035)*2:0;const vehicle=['concrete_truck','flatbed_truck','excavator'].includes(c.type)?Math.sin(tick*.012+i)*3:0;pos.set(x+moving+vehicle,y,z);euler.set(...c.transform.rotation.map(v=>THREE.MathUtils.degToRad(v)) as [number,number,number]);quat.setFromEuler(euler);
    if(cylinder){const r=dim(c,'radius',.3),h=dim(c,'height',1);scale.set(r*p,h*p,r*p)}else{const w=dim(c,'width',dim(c,'length',1)),h=dim(c,'height',1),d=dim(c,'depth',.5);const grow=c.type==='excavation'?Math.max(.01,p):p;scale.set(w*grow,h*grow,d*grow)}matrix.compose(pos,quat,scale);ref.current!.setMatrixAt(i,matrix)});ref.current.instanceMatrix.needsUpdate=true},[items,tick,section,cylinder,euler,matrix,pos,quat,scale]);
  const props=materialProps(items[0]?.materialId,mode);return <instancedMesh ref={ref} args={[undefined,undefined,items.length]} frustumCulled={false} castShadow={items[0]?.type!=='curtain_wall_panel'} receiveShadow onClick={(e:ThreeEvent<MouseEvent>)=>{e.stopPropagation();if(e.instanceId!==undefined)select(items[e.instanceId]?.id)}}>
    {cylinder?<cylinderGeometry args={[1,1,1,12]}/>:<boxGeometry args={[1,1,1]}/>}<meshStandardMaterial {...props} transparent={props.opacity<1} depthWrite={props.opacity>.4}/>
  </instancedMesh>
}

function Components(){const components=useStudio(s=>s.components),systems=useStudio(s=>s.systems),hidden=useStudio(s=>s.hiddenIds);const filtered=components.filter(c=>!hidden.includes(c.id)&&systems[systemFor(c)]&&c.type!=='tower_crane'&&c.type!=='crown'&&c.generator!=='cad_extruded_profile');const buckets=useMemo(()=>{const map=new Map<string,Component[]>();for(const c of filtered){const key=`${isCylinder(c)?'cyl':'box'}:${c.materialId??'concrete'}:${c.type==='excavation'?'excavation':'default'}`;map.set(key,[...(map.get(key)??[]),c])}return [...map.entries()]},[filtered]);return <>{buckets.map(([key,items])=><InstanceBucket key={key} items={items} cylinder={key.startsWith('cyl')}/>)}</>}

function CadPlanter(){const planter=useStudio(s=>s.components.find(c=>c.generator==='cad_extruded_profile')),tick=useStudio(s=>s.tick),shown=useStudio(s=>s.systems.landscape),select=useStudio(s=>s.select);const gltf=useGLTF('/assets/cad/planter.glb');const object=useMemo(()=>gltf.scene.clone(true),[gltf.scene]);useEffect(()=>{object.traverse(node=>{if(node instanceof THREE.Mesh){node.material=new THREE.MeshStandardMaterial({color:'#b7aa95',roughness:.82});node.castShadow=true;node.receiveShadow=true}})},[object]);if(!planter||!shown)return null;const p=visualProgress(planter,tick);return <group name="cad-planter-import" position={planter.transform.position} rotation={planter.transform.rotation.map(v=>THREE.MathUtils.degToRad(v)) as [number,number,number]} scale={[p,p,p]} onClick={e=>{e.stopPropagation();select(planter.id)}}><primitive object={object}/></group>}

function Crown(){const crown=useStudio(s=>s.components.find(c=>c.type==='crown')),tick=useStudio(s=>s.tick),mode=useStudio(s=>s.mode),select=useStudio(s=>s.select),section=useStudio(s=>s.camera);if(!crown||section==='section_x')return null;const p=visualProgress(crown,tick),h=dim(crown,'height',12),w=dim(crown,'width',20),taper=dim(crown,'taper',.58);return <group position={[0,112,0]} scale={[p,p,p]} onClick={e=>{e.stopPropagation();select(crown.id)}}>
  <mesh position={[0,-h*.26,0]} rotation={[0,Math.PI/4,0]} castShadow><cylinderGeometry args={[w*.5,w*.62,h*.48,4]}/><meshStandardMaterial {...materialProps(crown.materialId,mode)} /></mesh>
  <mesh position={[0,h*.24,0]} rotation={[0,Math.PI/4,0]} castShadow><cylinderGeometry args={[w*taper*.32,w*.5,h*.52,4]}/><meshStandardMaterial {...materialProps(crown.materialId,mode)} /></mesh>
  <group position={[0,h*.55,0]}>{Array.from({length:7},(_,i)=><mesh key={i} position={[-4.5+i*1.5,0,0]}><sphereGeometry args={[.55,8,6]}/><meshStandardMaterial color="#4f8a55" roughness={.9}/></mesh>)}</group>
  </group>}

function Crane(){const tick=useStudio(s=>s.tick),shown=useStudio(s=>s.systems.equipment),mode=useStudio(s=>s.mode);if(!shown)return null;const p=Math.min(1,tick/100),slew=Math.sin(tick*.009)*.4,trolley=6+Math.sin(tick*.026)*10,hookY=75+Math.sin(tick*.018)*18;const mat=materialProps('safety_orange',mode);return <group position={[25,0,12]} scale={[1,p,1]} rotation={[0,slew,0]}>
  <mesh position={[0,62,0]} castShadow><boxGeometry args={[1.4,124,1.4]}/><meshStandardMaterial {...mat}/></mesh><mesh position={[-8,123,0]} castShadow><boxGeometry args={[34,1.1,1.1]}/><meshStandardMaterial {...mat}/></mesh><mesh position={[13,123,0]}><boxGeometry args={[8,2,2.4]}/><meshStandardMaterial color="#273139" metalness={.65}/></mesh>
  <Line points={[[trolley,122.5,0],[trolley,hookY,0]]} color="#252b2e" lineWidth={1}/><mesh position={[trolley,hookY,0]}><boxGeometry args={[2,.6,2]}/><meshStandardMaterial color="#d38d3f"/></mesh>
  </group>}

function Selection(){const id=useStudio(s=>s.selectedId),components=useStudio(s=>s.components),tick=useStudio(s=>s.tick);const c=components.find(x=>x.id===id);if(!c||c.type==='crown')return null;const p=visualProgress(c,tick);if(p<=0)return null;const w=dim(c,'width',dim(c,'radius',.3)*2),h=dim(c,'height',1),d=dim(c,'depth',dim(c,'radius',.3)*2);return <mesh position={c.transform.position} rotation={c.transform.rotation.map(v=>THREE.MathUtils.degToRad(v)) as [number,number,number]}><boxGeometry args={[w*1.05,h*1.05,d*1.05]}/><meshBasicMaterial color="#ffd27d" wireframe transparent opacity={.95}/></mesh>}

function DemolitionBursts(){const bursts=useStudio(s=>s.demolitionBursts);return <>{bursts.map(({component,progress})=>{const w=Math.max(.35,dim(component,'width',dim(component,'radius',.5)*2)),h=Math.max(.35,dim(component,'height',1)),d=Math.max(.35,dim(component,'depth',dim(component,'radius',.5)*2));return <group key={component.id} position={component.transform.position}>{Array.from({length:8},(_,i)=>{const angle=i/8*Math.PI*2,spread=progress*(1.4+Math.min(3,w*.12)),fall=progress*progress*(2.4+Math.min(4,h*.08));return <mesh key={i} position={[Math.cos(angle)*spread,(i%3-1)*h*.12*progress-fall,Math.sin(angle)*spread]} rotation={[progress*(i+1),progress*i*.7,progress*i*.3]}><boxGeometry args={[Math.max(.12,w*.22),Math.max(.12,h*.16),Math.max(.12,d*.22)]}/><meshStandardMaterial color={i%2?'#bd7847':'#667276'} roughness={.88} transparent opacity={1-progress*.75}/></mesh>})}<mesh position={[0,-fallDistance(progress,h),0]} scale={1+progress*2.5}><sphereGeometry args={[Math.max(.5,Math.min(2,w*.12)),8,6]}/><meshStandardMaterial color="#9a8c79" transparent opacity={Math.max(0,.34-progress*.34)} depthWrite={false}/></mesh></group>})}</>}
function fallDistance(progress:number,height:number){return progress*progress*Math.min(3,height*.08)}

const views={overview:{pos:[95,180,105],target:[0,45,0]},street:{pos:[38,6,-32],target:[0,18,0]},crane:{pos:[-18,108,58],target:[15,76,7]},section_x:{pos:[88,54,0],target:[0,48,0]},section_z:{pos:[0,54,88],target:[0,48,0]},top:{pos:[.01,160,.01],target:[0,0,0]}} as const;
function CameraRig(){const preset=useStudio(s=>s.camera),selectedId=useStudio(s=>s.selectedId),components=useStudio(s=>s.components),{camera}=useThree(),controls=useRef<any>(null);const selected=components.find(c=>c.id===selectedId);const v=useMemo(()=>preset==='selected'&&selected?{pos:[selected.transform.position[0]+15,selected.transform.position[1]+10,selected.transform.position[2]+15] as const,target:selected.transform.position}:views[preset==='selected'?'overview':preset],[preset,selected]);useEffect(()=>{camera.position.set(v.pos[0],v.pos[1],v.pos[2]);camera.lookAt(v.target[0],v.target[1],v.target[2]);if(camera instanceof THREE.PerspectiveCamera){camera.fov=preset==='street'?62:42;camera.updateProjectionMatrix()}if(controls.current){controls.current.target.set(v.target[0],v.target[1],v.target[2]);controls.current.update()}},[camera,preset,v]);return <OrbitControls ref={controls} makeDefault target={[v.target[0],v.target[1],v.target[2]]} enableDamping dampingFactor={.08} minDistance={4} maxDistance={240} maxPolarAngle={Math.PI*.495}/>}

function Lighting(){const mode=useStudio(s=>s.mode);const night=mode==='night';return <><ambientLight intensity={night?.28:.65}/><hemisphereLight intensity={night?.35:.75} color={night?'#7394c8':'#d8edff'} groundColor="#1c2428"/><directionalLight position={[45,95,35]} intensity={night?.35:2.2} color={night?'#8ba8d8':'#fff1d7'} castShadow shadow-mapSize={[2048,2048]} shadow-camera-far={240} shadow-camera-left={-85} shadow-camera-right={85} shadow-camera-top={120} shadow-camera-bottom={-50}/>{night?<Stars radius={170} depth={70} count={1500} factor={3}/>:<Sky distance={450000} sunPosition={[60,35,45]} turbidity={7} rayleigh={1.5}/>}<fog attach="fog" args={[night?'#071018':'#b8c9ce',100,260]}/></>}

function SceneReady(){const {gl,camera,scene,invalidate}=useThree();useEffect(()=>{(window as any).__SKYFOUNDRY_CANVAS__=gl.domElement;(window as any).__SKYFOUNDRY_RENDERER__=gl;(window as any).__SKYFOUNDRY_CAMERA__=camera;(window as any).__SKYFOUNDRY_SCENE__=scene;invalidate();const first=requestAnimationFrame(()=>requestAnimationFrame(()=>{if(!gl.getContext().isContextLost()&&gl.info.render.calls>0)document.documentElement.dataset.sceneReady='true'}));return()=>{cancelAnimationFrame(first);delete document.documentElement.dataset.sceneReady;delete (window as any).__SKYFOUNDRY_CANVAS__;delete (window as any).__SKYFOUNDRY_RENDERER__}},[gl,camera,scene,invalidate]);return null}

export default function Scene(){const mode=useStudio(s=>s.mode),select=useStudio(s=>s.select);return <Canvas data-testid="construction-canvas" frameloop="demand" shadows={false} dpr={1} camera={{position:[95,180,105],fov:42,near:.1,far:600}} gl={{antialias:false,preserveDrawingBuffer:false,localClippingEnabled:true}} onPointerMissed={()=>select(undefined)}>
  <color attach="background" args={[mode==='night'?'#071018':'#b8c9ce']}/><Lighting/><CityContext/><Components/><Suspense fallback={null}><CadPlanter/></Suspense><Crown/><Crane/><DemolitionBursts/><Selection/><CameraRig/><SceneReady/><Html position={[0,118,0]} center distanceFactor={30} style={{pointerEvents:'none'}}><div className="scene-label">SKYFOUNDRY / TOWER A</div></Html>
  </Canvas>}
